// Builds an idempotent SQL migration that writes official names, listing
// identity, market caps and size tiers onto existing company records.
// Usage: node scripts/market-cap-migration.ts data/company-market-caps-2026-09-23.csv 2026-09-23 > supabase/migrations/<name>.sql
// The CSV's company-name column is unquoted and may contain commas, so rows are
// read from both ends: 8 fixed leading columns, 7 fixed trailing columns.
import { readFileSync } from "node:fs";
import {
  parseMarketCap,
  sizeFromMarketCap,
} from "../supabase/functions/_shared/company-size.ts";

export function splitCsvLine(line: string) {
  const out: string[] = [];
  let cur = "",
    quoted = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (quoted) {
      if (ch === '"' && line[i + 1] === '"') (cur += '"'), i++;
      else if (ch === '"') quoted = false;
      else cur += ch;
    } else if (ch === '"') quoted = true;
    else if (ch === ",") out.push(cur), (cur = "");
    else cur += ch;
  }
  out.push(cur);
  return out;
}

export interface MarketCapRow {
  id: string;
  officialName: string;
  ticker: string;
  exchange: string;
  country: string;
  marketCapUsd: number;
}

export function parseRows(csv: string): MarketCapRow[] {
  return csv
    .split(/\r?\n/)
    .slice(1)
    .filter((l) => l.trim())
    .map((line) => {
      const f = splitCsvLine(line);
      const tail = f.slice(-7);
      const middle = f.slice(8, -7);
      // middle = [name_hint, (blank)…, official name split on commas]
      const rest = middle.slice(1);
      while (rest.length > 1 && !rest[0].trim()) rest.shift();
      const [ticker, exchange, country, , , , cap] = tail;
      const marketCapUsd = parseMarketCap(cap);
      if (!f[0] || marketCapUsd === null)
        throw new Error(`Unreadable row: ${line}`);
      const unlisted = /^unlisted$/i.test(exchange.trim());
      return {
        id: f[0].trim(),
        officialName: rest.join(",").trim(),
        ticker: unlisted ? "" : ticker.trim(),
        exchange: unlisted ? "" : exchange.trim(),
        country: country.trim(),
        marketCapUsd,
      };
    });
}

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

export function migrationSql(rows: MarketCapRow[], asOf: string) {
  const values = rows
    .map(
      (r) =>
        ` (${q(r.id)},${q(r.officialName)},${q(r.ticker)},${q(r.exchange)},${q(r.country)},${r.marketCapUsd},${q(sizeFromMarketCap(r.marketCapUsd))})`,
    )
    .join(",\n");
  return `-- Market caps as of ${asOf} with official names and listings (generated by
-- scripts/market-cap-migration.ts from data/). Idempotent: re-running rewrites
-- the same values. A ticker/exchange already on the record is kept; the size
-- tier is derived from market cap unless the owner chose one manually.
begin;
with src(id,official,ticker,exchange,country,cap,size) as (values
${values}
)
update public.desk_records r set
 data = r.data || jsonb_build_object(
   'officialName', s.official,
   'country', s.country,
   'ticker', case when coalesce(r.data->>'ticker','')='' then s.ticker else r.data->>'ticker' end,
   'exchange', case when coalesce(r.data->>'exchange','')='' then s.exchange else r.data->>'exchange' end,
   'marketCapUsd', s.cap,
   'marketCapAsOf', ${q(asOf)},
   'sizeClass', case when r.data->>'sizeSource'='manual' then r.data->>'sizeClass' else s.size end,
   'sizeSource', case when r.data->>'sizeSource'='manual' then 'manual' else 'market_cap' end,
   'newsRevision', coalesce((r.data->>'newsRevision')::int,1)+1,
   'revision', coalesce((r.data->>'revision')::int,1)+1,
   'updatedAt', to_char(now() at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
 version = r.version+1,
 updated_at = now()
from src s
where r.kind='company' and r.id=s.id
 and (r.data->>'marketCapUsd' is distinct from s.cap::text or r.data->>'officialName' is distinct from s.official);
commit;
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const [file, asOf = "2026-09-23"] = process.argv.slice(2);
  if (!file) throw new Error("Usage: market-cap-migration.ts <csv> [asOf]");
  process.stdout.write(migrationSql(parseRows(readFileSync(file, "utf8")), asOf));
}
